<Project Sdk="Dalamud.CN.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.1.2</Version>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <AssemblyName>CrescentCompass</AssemblyName>
    <RootNamespace>CrescentCompass</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <DebugType>embedded</DebugType>
    <Optimize>true</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CrescentCompass.Core\CrescentCompass.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="images\icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
